exclude: '.git|.direnv'
default_stages: [commit]
fail_fast: true

repos:
- repo: local
  hooks:
    - id: jupyter-nb-clear-output
      name: jupyter-nb-clear-output
      files: \.ipynb$
      language: system
      entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
